### ISSUE TITLE
Implementar EFCore

### ISSUE THREAD

**Issue by patrickhacens** [lucass-teixeira/ContosoPizza#17]
Vamos implementar um ORM (EntityFrameworkCore) para acessar os dados do banco.

- [x] Adicionar os pacotes necessários
- [x] Fazer injeção de dependencia
- [x] Alterar os handlers de pizza para acessar o banco com a EF
- [x] Alterar os handlers de toppings para acessar o banco com a EF

**Comment by LucasFelicianoAlmeida** [comment]
Eu devo fazer alguma pattern nos handlers?
